### ISSUE TITLE
Investigar modelos 3D

### ISSUE THREAD

**Issue by Eduardogallegos** [Eduardogallegos/proyecto-final-graficas#4]
Investigar librerías o fuentes para obtener los modelos 3D que se usarán en el proyecto.

**Comment by Eduardogallegos** [comment]
Yo encontré [aquí](https://free3d.com/es/modelos-3d/obj) objetios gratis para [manos](https://free3d.com/es/modelo-3d/rigged-hands-28855.html), [escuadra y cuerno de chivo](https://free3d.com/es/modelo-3d/pack-of-15-modern-weapons-6-attachments-734779.html), [picahielos](https://free3d.com/es/modelo-3d/sting-sword-128810.html), [motobici](https://free3d.com/es/modelo-3d/moto-rickshaw-v1--205434.html), [humbee](https://free3d.com/es/modelo-3d/humvee-vehicle-49947.html), [politec](https://free3d.com/es/modelo-3d/model-without-textured-for-games-81527.html), [muebles de oficina](https://free3d.com/es/modelo-3d/set-of-furniture-2-164165.html), [planta](https://free3d.com/es/modelo-3d/house-plant-03-78195.html), [carrito de hot dogs](https://free3d.com/es/modelo-3d/street-food-cart-270694.html) y [edificio](https://free3d.com/es/modelo-3d/historic-buildings-13655.html)

**Comment by JavierZavala17** [comment]
Yo encontré [este ](https://threejs.org/examples/#webgl_loader_md2)que podriamos usar como enemigo en fase _beta_, tiene ya animación de caminar entonces eso facilitaría el demonstrar la pausa del tiempo, tiene opciones de armas y todo, solo sería cambiarle la skin y listo

**Comment by PedroCorsob** [comment]
[Edificios](https://www.turbosquid.com/3d-models/skyscrapers-sky-model-1690420), [muebles](https://www.turbosquid.com/Search/3D-Models/free/furniture/fbx.), [carros](https://www.cgtrader.com/free-3d-models/car), [oficinas](https://www.cgtrader.com/free-3d-models/office) y [armas](https://www.cgtrader.com/free-3d-models/gun) que podemos utilizar.
