### ISSUE TITLE
Física de la escena

### ISSUE THREAD

**Issue by Eduardogallegos** [Eduardogallegos/proyecto-final-graficas#8]
Implementar la física para que la cámara interactúe con la escena, es decir que no atraviese las paredes, sino que choque con ellas.

**Comment by Eduardogallegos** [comment]
https://stackoverflow.com/questions/29202480/three-js-calculating-vertex-normals

Para arreglar las normales de la oficina

**Comment by JavierZavala17** [comment]
https://schteppe.github.io/cannon.js/
